# Generated by Django 3.1.3 on 2020-11-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lastface_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('employee', 'employee'), ('visitor', 'visitor')], default='employee', max_length=20, null=True),
        ),
    ]
