# Generated by Django 3.1.3 on 2020-11-28 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Shift',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
