# Generated by Django 3.1.3 on 2020-11-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Shift',
            new_name='shift',
        ),
    ]
